services:
  - type: web
    name: email-classifier-backend
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet')"
    startCommand: python -m src.main
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
