services:
  - type: web
    name: email-classifier-frontend
    env: node
    branch: feat_preparing_to_deploy_front_end_2
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://email-classifier-wsdr.onrender.com
